<h2>Lista de categorias</h2>
 
 <?php
      echo $this->Html->link(
        "Agregar Categoria",
        array(
          "controller"=>"categorias",
          "method"=>"agregar",
        )
      );?>


  <?php
      echo $this->Html->link(
        "Lista de tareas",
        array(
          "controller"=>"tareas",
          "method"=>"index",
        )
      );?>


<br>
<table border="1px">
  <tr>
    <th>ID</th>
    <th>Nombre</th>
    <th>Accion</th>

  </tr>
  <?php foreach ($categorias as $categoria): ?>
  <tr>
    <td><?php echo $categoria["categorias"]["id"]; ?></td>
    <td><?php echo $categoria["categorias"]["nombre"]; ?></td>
    <td>
      <?php
      echo $this->Html->link(
        "Editar",
        array(
          "controller"=>"categorias",
          "method"=>"editar",
          "args"=>$categoria["categorias"]["id"]
        ),
        array(
          "title"=>"Editar categoria",

        )
      );
      echo " | ";
      echo $this->Html->link(
        "Eliminar",
        array(
          "controller"=>"categorias",
          "method"=>"eliminar",
          "args"=>$categoria["categorias"]["id"]
        ),
        array(
          "id"=>"eliminar". " ".$categoria["categorias"]["id"],
          "class"=>"class"
        )
      );

       ?>
    </td>
  </tr>
<?php endforeach; ?>
</table>
