<h2></h2>

<form action="<?php echo APP_URL; ?>/tareas/editar" method="POST">
  <fieldset>
					<legend>Editar tarea</legend>

  <div >
  <input type="hidden" name="id" value="<?php echo $tarea["id"]; ?>">
  <p>
    <label for="nombre">Nombre: </label>
    <input value="<?php echo $tarea["nombre"]; ?>">
  </p>

  <p>
    <label for="descripcion">Descripcion: </label>
    <input type="textarea" name="descripcion" value="<?php echo $tarea["descripcion"]; ?>">
  </p>
  <p>
    <label for="categoria">Categoría: </label>
    <select name="categoria_id">
      <?php
        foreach ($categorias as $categoria):
          if ($tarea["categoria_id"]==$categoria["categorias"]["id"]) { ?>
          <option selected value="<?php echo $categoria["categorias"]['id']?>">
            <?php echo $categoria["categorias"]["nombre"]; ?>
          </option>
          <?php } else { ?>
          <option value="<?php echo $categoria["categorias"]['id']?>">
            <?php echo $categoria["categorias"]["nombre"]; }?>
          </option>

        <?php endforeach; ?>
    </select>
  </p>
  <p>
    <label for="fecha">Fecha: </label>
    <input  type="date" name="fecha" value="<?php echo $tarea["fecha"]; ?>">
  </p>
  <p>
    <label for="prioridad">Prioridad: </label>
    <input type="range" name="prioridad" min="1" max="10" value="<?php echo $tarea["prioridad"]; ?>">
  </p>
  <p>
    <label for="fecha">Estatus: </label>
    <input  type="text" name="status" value="<?php echo $tarea["status"]; ?>">
  </p>
  <p>
    <input type="submit">
  </p>
</div>
</fieldset>
</form>
